version: 1
directus: 14.0.2
vendor: postgres
collections: []
fields: []
relations:
  - collection: directus_settings
    field: public_favicon
    related_collection: directus_files
    meta: null
    schema:
      table: directus_settings
      column: public_favicon
      foreign_key_table: directus_files
      foreign_key_column: id
      constraint_name: directus_settings_public_favicon_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
